# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'wienwahl.ui'
#
# Created: Mon Apr 11 16:36:34 2016
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Wienwahl(object):
    def setupUi(self, Wienwahl):
        Wienwahl.setObjectName("Wienwahl")
        Wienwahl.resize(852, 506)
        self.centralWidget = QtGui.QWidget(Wienwahl)
        self.centralWidget.setObjectName("centralWidget")
        self.tableView = QtGui.QTableView(self.centralWidget)
        self.tableView.setGeometry(QtCore.QRect(10, 10, 831, 441))
        self.tableView.setObjectName("tableView")
        Wienwahl.setCentralWidget(self.centralWidget)
        self.statusBar = QtGui.QStatusBar(Wienwahl)
        self.statusBar.setObjectName("statusBar")
        Wienwahl.setStatusBar(self.statusBar)
        self.menuBar = QtGui.QMenuBar(Wienwahl)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 852, 27))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtGui.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtGui.QMenu(self.menuBar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuDatabase = QtGui.QMenu(self.menuBar)
        self.menuDatabase.setObjectName("menuDatabase")
        Wienwahl.setMenuBar(self.menuBar)
        self.actionNeu_STRG_N = QtGui.QAction(Wienwahl)
        self.actionNeu_STRG_N.setObjectName("actionNeu_STRG_N")
        self.action_ffnen_STRG_O = QtGui.QAction(Wienwahl)
        self.action_ffnen_STRG_O.setObjectName("action_ffnen_STRG_O")
        self.actionSave_STRG_S = QtGui.QAction(Wienwahl)
        self.actionSave_STRG_S.setObjectName("actionSave_STRG_S")
        self.actionSave_As = QtGui.QAction(Wienwahl)
        self.actionSave_As.setObjectName("actionSave_As")
        self.actionOpen = QtGui.QAction(Wienwahl)
        self.actionOpen.setObjectName("actionOpen")
        self.actionNew = QtGui.QAction(Wienwahl)
        self.actionNew.setObjectName("actionNew")
        self.actionSave = QtGui.QAction(Wienwahl)
        self.actionSave.setObjectName("actionSave")
        self.actionSaveAs = QtGui.QAction(Wienwahl)
        self.actionSaveAs.setObjectName("actionSaveAs")
        self.actionExit = QtGui.QAction(Wienwahl)
        self.actionExit.setObjectName("actionExit")
        self.actionAddNewRow = QtGui.QAction(Wienwahl)
        self.actionAddNewRow.setObjectName("actionAddNewRow")
        self.actionDuplicateRow = QtGui.QAction(Wienwahl)
        self.actionDuplicateRow.setObjectName("actionDuplicateRow")
        self.actionDeleteRow = QtGui.QAction(Wienwahl)
        self.actionDeleteRow.setObjectName("actionDeleteRow")
        self.actionCopy = QtGui.QAction(Wienwahl)
        self.actionCopy.setObjectName("actionCopy")
        self.actionPaste = QtGui.QAction(Wienwahl)
        self.actionPaste.setObjectName("actionPaste")
        self.actionCut = QtGui.QAction(Wienwahl)
        self.actionCut.setObjectName("actionCut")
        self.actionUndo = QtGui.QAction(Wienwahl)
        self.actionUndo.setObjectName("actionUndo")
        self.actionRedo = QtGui.QAction(Wienwahl)
        self.actionRedo.setObjectName("actionRedo")
        self.actionSaveToDB = QtGui.QAction(Wienwahl)
        self.actionSaveToDB.setObjectName("actionSaveToDB")
        self.actionLoadFromDB = QtGui.QAction(Wienwahl)
        self.actionLoadFromDB.setObjectName("actionLoadFromDB")
        self.actionGenerateProjection = QtGui.QAction(Wienwahl)
        self.actionGenerateProjection.setObjectName("actionGenerateProjection")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSaveAs)
        self.menuFile.addAction(self.actionExit)
        self.menuEdit.addAction(self.actionAddNewRow)
        self.menuEdit.addAction(self.actionDuplicateRow)
        self.menuEdit.addAction(self.actionDeleteRow)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionCopy)
        self.menuEdit.addAction(self.actionCut)
        self.menuEdit.addAction(self.actionPaste)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionUndo)
        self.menuEdit.addAction(self.actionRedo)
        self.menuDatabase.addAction(self.actionSaveToDB)
        self.menuDatabase.addAction(self.actionLoadFromDB)
        self.menuDatabase.addSeparator()
        self.menuDatabase.addAction(self.actionGenerateProjection)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuEdit.menuAction())
        self.menuBar.addAction(self.menuDatabase.menuAction())

        self.retranslateUi(Wienwahl)
        QtCore.QMetaObject.connectSlotsByName(Wienwahl)

    def retranslateUi(self, Wienwahl):
        Wienwahl.setWindowTitle(QtGui.QApplication.translate("Wienwahl", "Wienwahl", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("Wienwahl", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuEdit.setTitle(QtGui.QApplication.translate("Wienwahl", "Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.menuDatabase.setTitle(QtGui.QApplication.translate("Wienwahl", "Database", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNeu_STRG_N.setText(QtGui.QApplication.translate("Wienwahl", "Neu... [STRG+N]", None, QtGui.QApplication.UnicodeUTF8))
        self.action_ffnen_STRG_O.setText(QtGui.QApplication.translate("Wienwahl", "Öffnen... [STRG+O]", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_STRG_S.setText(QtGui.QApplication.translate("Wienwahl", "Save... [STRG+S]", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_As.setText(QtGui.QApplication.translate("Wienwahl", "Save As...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen.setText(QtGui.QApplication.translate("Wienwahl", "Open", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew.setText(QtGui.QApplication.translate("Wienwahl", "New", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setText(QtGui.QApplication.translate("Wienwahl", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSaveAs.setText(QtGui.QApplication.translate("Wienwahl", "Save as", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setText(QtGui.QApplication.translate("Wienwahl", "Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAddNewRow.setText(QtGui.QApplication.translate("Wienwahl", "Add new row", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDuplicateRow.setText(QtGui.QApplication.translate("Wienwahl", "Duplicate row", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDeleteRow.setText(QtGui.QApplication.translate("Wienwahl", "Delete row", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCopy.setText(QtGui.QApplication.translate("Wienwahl", "Copy", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPaste.setText(QtGui.QApplication.translate("Wienwahl", "Paste", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCut.setText(QtGui.QApplication.translate("Wienwahl", "Cut", None, QtGui.QApplication.UnicodeUTF8))
        self.actionUndo.setText(QtGui.QApplication.translate("Wienwahl", "Undo", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRedo.setText(QtGui.QApplication.translate("Wienwahl", "Redo", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSaveToDB.setText(QtGui.QApplication.translate("Wienwahl", "Save to DB", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLoadFromDB.setText(QtGui.QApplication.translate("Wienwahl", "Load from DB", None, QtGui.QApplication.UnicodeUTF8))
        self.actionGenerateProjection.setText(QtGui.QApplication.translate("Wienwahl", "Generate projection", None, QtGui.QApplication.UnicodeUTF8))

